---

- name: Configure monitoring
  template:
    src: etc/monit/conf-available/postgres.j2
    dest: /etc/monit/conf-available/postgres
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Monit

- name: Enable Monit configuration
  file:
    src: "/etc/monit/conf-available/postgres"
    dest: /etc/monit/conf-enabled/postgres
    state: link
  notify:
    - Reload Monit
